import { z } from "zod";

export const EventTypeSchema = z.enum([
  "run.created",
  "run.started",
  "run.waiting",
  "run.resumed",
  "model.final.proposed",
  "model.final.rejected",
  "model.final.accepted",
  "model.action.generated",
  "model.action.rejected",
  "model.started",
  "model.completed",
  "command.started",
  "command.completed",
  "command.failed",
  "patch.applied",
  "search.completed",
  "working-set.built",
  "ledger.initialized",
  "ledger.updated",
  "iteration.started",
  "iteration.completed",
  "iteration.failed",
  "budget.checked",
  "budget.exceeded",
  "no_progress.detected",
  "reground.requested",
  "replan.requested",
  "tool.started",
  "tool.completed",
  "tool.failed",
  "approval.requested",
  "approval.approved",
  "approval.denied",
  "approval.expired",
  "user_input.requested",
  "user_input.received",
  "context.compacted",
  "context.regrounded",
  "context.integrity_violation",
  "checkpoint.created",
  "checkpoint.loaded",
  "recovery.decision",
  "recovery.reconciled",
  "recovery.rejected",
  "artifact.created",
  "validation.started",
  "validation.completed",
  "repository.discovery.started",
  "repository.discovery.completed",
  "repository.discovery.failed",
  "repository.profile.created",
  "repository.profile.updated",
  "repository.profile.invalidated",
  "repository.regrounded",
  "project.commands.discovered",
  "project.integration-candidates.discovered",
  "git.status.completed",
  "git.diff.completed",
  "working-set.built",
  "working-set.invalidated",
  "context.manifest.updated",
  "bugfix.issue.loaded",
  "bugfix.reproduction.started",
  "bugfix.reproduction.completed",
  "bugfix.reproduction.failed",
  "bugfix.root-cause.proposed",
  "bugfix.plan.created",
  "bugfix.plan.updated",
  "bugfix.patch.started",
  "bugfix.patch.completed",
  "bugfix.patch.failed",
  "bugfix.verification.started",
  "bugfix.verification.completed",
  "bugfix.verification.failed",
  "bugfix.diff-review.completed",
  "bugfix.completion-gate.passed",
  "bugfix.completion-gate.failed",
  "fixture.setup.completed",
  "fixture.run.completed",
  "fixture.cleanup.completed",
  "fixture.suite.completed",
  "feature.requirement.loaded",
  "feature.architecture.mapped",
  "feature.contract.designed",
  "feature.plan.created",
  "feature.stage.started",
  "feature.stage.completed",
  "feature.stage.blocked",
  "feature.data.change.started",
  "feature.data.change.completed",
  "feature.data.change.failed",
  "feature.contract.mismatch",
  "feature.e2e.started",
  "feature.e2e.completed",
  "feature.e2e.failed",
  "feature.diff-review.completed",
  "feature.completion-gate.passed",
  "feature.completion-gate.failed",
  "feature.run.completed",
  "feature.cleanup.completed",
  "feature.suite.completed",
  "run.completed",
  "run.failed"
]);

export const EventSchema = z.object({
  eventVersion: z.literal("1"),
  eventId: z.string().min(1),
  runId: z.string().min(1),
  sequence: z.number().int().positive(),
  type: EventTypeSchema,
  timestamp: z.string().datetime(),
  payload: z.record(z.string(), z.unknown())
});

export type Event = z.infer<typeof EventSchema>;
export type EventType = z.infer<typeof EventTypeSchema>;

export function createEvent(input: {
  eventId: string;
  runId: string;
  sequence: number;
  type: EventType;
  timestamp: string;
  payload: Record<string, unknown>;
}): Event {
  return EventSchema.parse({
    eventVersion: "1",
    eventId: input.eventId,
    runId: input.runId,
    sequence: input.sequence,
    type: input.type,
    timestamp: input.timestamp,
    payload: input.payload
  });
}
