import { readFileSync } from "node:fs";
import { extname } from "node:path";

import {
  AlignmentType,
  Document,
  HeadingLevel,
  ImageRun,
  LevelFormat,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
  type FileChild,
  type IParagraphOptions
} from "docx";
import { strFromU8, unzipSync } from "fflate";

import type {
  InlineRun,
  RichDocumentBlock,
  RichDocumentLeafBlock,
  RichDocumentSource
} from "./contracts.js";

export type DocxValidation = {
  readonly format: "docx";
  readonly byteLength: number;
  readonly paragraphCount: number;
  readonly tableCount: number;
  readonly imageCount: number;
  readonly packageEntryCount: number;
};

const MAX_DOCX_BYTES = 50_000_000;

export async function renderDocx(
  source: RichDocumentSource,
  resolveAsset: (workspacePath: string) => string
): Promise<{ readonly bytes: Buffer; readonly validation: DocxValidation }> {
  const counters = { paragraphs: 0, tables: 0, images: 0 };
  const children = source.blocks.flatMap((block) => renderBlock(block, source, resolveAsset, counters));
  const document = new Document({
    creator: "Nexora",
    title: source.title,
    description: "Generated by the Nexora Office capability.",
    numbering: {
      config: [{
        reference: "nexora-numbering",
        levels: [{
          level: 0,
          format: LevelFormat.DECIMAL,
          text: "%1.",
          alignment: AlignmentType.START,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } }
        }]
      }]
    },
    styles: {
      default: {
        document: {
          run: { font: source.theme.font === "serif" ? "Georgia" : "Aptos", size: 22 },
          paragraph: { spacing: { after: source.theme.spacing === "compact" ? 100 : 180, line: 300 } }
        }
      }
    },
    sections: [{ properties: {}, children }]
  });
  const bytes = Buffer.from(await Packer.toBuffer(document));
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_DOCX_BYTES) {
    throw new Error(`Generated DOCX byte length ${bytes.byteLength} is outside the safe limit.`);
  }
  const packageValidation = validateDocxPackage(bytes);
  return {
    bytes,
    validation: {
      format: "docx",
      byteLength: bytes.byteLength,
      paragraphCount: counters.paragraphs,
      tableCount: counters.tables,
      imageCount: counters.images,
      packageEntryCount: packageValidation.packageEntryCount
    }
  };
}

export function validateDocxPackage(bytes: Uint8Array): { readonly packageEntryCount: number } {
  let entries: Record<string, Uint8Array>;
  try { entries = unzipSync(bytes); }
  catch (error) { throw new Error(`Generated DOCX is not a readable ZIP package: ${error instanceof Error ? error.message : String(error)}`); }
  for (const required of ["[Content_Types].xml", "_rels/.rels", "word/document.xml"]) {
    if (entries[required] === undefined) throw new Error(`Generated DOCX is missing required package entry ${required}.`);
  }
  const forbidden = Object.keys(entries).find((name) => /(?:vbaProject|activeX|embeddings|customUI)/iu.test(name));
  if (forbidden !== undefined) throw new Error(`Generated DOCX contains forbidden active content: ${forbidden}.`);
  const documentXml = strFromU8(entries["word/document.xml"]!);
  if (!/<w:document\b/u.test(documentXml) || !/<w:body>/u.test(documentXml)) {
    throw new Error("Generated DOCX document.xml does not contain a Word document body.");
  }
  const relationships = Object.entries(entries)
    .filter(([name]) => name.endsWith(".rels"))
    .map(([, value]) => strFromU8(value))
    .join("\n");
  if (/TargetMode=["']External["']/iu.test(relationships)) {
    throw new Error("Generated DOCX contains an external relationship.");
  }
  return { packageEntryCount: Object.keys(entries).length };
}

export function readDocxDocumentXml(bytes: Uint8Array): string {
  const entries = unzipSync(bytes);
  const document = entries["word/document.xml"];
  if (document === undefined) throw new Error("DOCX package is missing word/document.xml.");
  return strFromU8(document);
}

function renderBlock(
  block: RichDocumentBlock,
  source: RichDocumentSource,
  resolveAsset: (workspacePath: string) => string,
  counters: { paragraphs: number; tables: number; images: number }
): FileChild[] {
  if (block.type !== "columns") return renderLeaf(block, source, resolveAsset, counters);
  counters.tables += 1;
  return [new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [new TableRow({
      children: block.columns.map((column) => new TableCell({
        width: { size: Math.floor(100 / block.columns.length), type: WidthType.PERCENTAGE },
        children: column.flatMap((item) => renderLeaf(item, source, resolveAsset, counters))
      }))
    })]
  })];
}

function renderLeaf(
  block: RichDocumentLeafBlock,
  source: RichDocumentSource,
  resolveAsset: (workspacePath: string) => string,
  counters: { paragraphs: number; tables: number; images: number }
): FileChild[] {
  switch (block.type) {
    case "heading": {
      counters.paragraphs += 1;
      const heading = [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3, HeadingLevel.HEADING_4][block.level - 1]!;
      return [paragraph(block.runs, counters, {
        heading,
        spacing: { before: block.level === 1 ? 280 : 180, after: 120 }
      }, source.theme.primaryColor.slice(1))];
    }
    case "paragraph": return [paragraph(block.runs, counters)];
    case "list": return block.items.map((runs) => {
      counters.paragraphs += 1;
      return new Paragraph({
        children: textRuns(runs),
        ...(block.ordered
          ? { numbering: { reference: "nexora-numbering", level: 0 } }
          : { bullet: { level: 0 } })
      });
    });
    case "table": {
      counters.tables += 1;
      if (block.caption !== undefined) counters.paragraphs += 1;
      return [
        ...(block.caption === undefined ? [] : [paragraph(block.caption, counters, { alignment: AlignmentType.CENTER })]),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({
              tableHeader: true,
              children: block.headers.map((runs) => cell(runs, counters, true))
            }),
            ...block.rows.map((row) => new TableRow({ children: row.map((runs) => cell(runs, counters, false)) }))
          ]
        })
      ];
    }
    case "metric": {
      counters.tables += 1;
      return [new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [new TableRow({ children: [
          new TableCell({ shading: { type: ShadingType.CLEAR, fill: source.theme.accentColor.slice(1) }, children: [paragraph(block.label, counters)] }),
          new TableCell({ children: [paragraph(block.value, counters)] }),
          ...(block.delta === undefined ? [] : [new TableCell({ children: [paragraph(block.delta, counters)] })])
        ] })]
      }), ...(block.note === undefined ? [] : [paragraph(block.note, counters)])];
    }
    case "callout": {
      counters.tables += 1;
      const fill = block.tone === "warning" ? "FEF3C7" : block.tone === "success" ? "DCFCE7" : "DBEAFE";
      return [new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [new TableRow({ children: [new TableCell({ shading: { type: ShadingType.CLEAR, fill }, children: [paragraph(block.runs, counters)] })] })]
      })];
    }
    case "image": {
      const assetPath = resolveAsset(block.assetPath);
      const extension = extname(assetPath).toLowerCase();
      if (![".png", ".jpg", ".jpeg"].includes(extension)) {
        throw new Error(`DOCX supports PNG and JPEG image assets; ${block.assetPath} is ${extension || "unknown"}.`);
      }
      counters.images += 1;
      counters.paragraphs += 1;
      const image = new ImageRun({
        type: extension === ".png" ? "png" : "jpg",
        data: readFileSync(assetPath),
        transformation: { width: 560, height: 315 },
        altText: { title: block.alt, description: block.alt, name: block.blockId }
      });
      return [
        new Paragraph({ children: [image], alignment: AlignmentType.CENTER }),
        ...(block.caption === undefined ? [] : [paragraph(block.caption, counters, { alignment: AlignmentType.CENTER })])
      ];
    }
    case "chart": {
      counters.paragraphs += 1;
      counters.tables += 1;
      const headers: InlineRun[][] = [[{ text: block.title ?? "Chart" }], ...block.series.map(({ name }) => [{ text: name }])];
      const rows = block.categories.map((category, index) => [
        [{ text: category }],
        ...block.series.map(({ values }) => [{ text: String(values[index] ?? "") }])
      ]);
      return [
        paragraph([{ text: `${block.title ?? "Chart"} (${block.chartType})`, bold: true }], counters),
        new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [
          new TableRow({ tableHeader: true, children: headers.map((runs) => cell(runs, counters, true)) }),
          ...rows.map((row) => new TableRow({ children: row.map((runs) => cell(runs, counters, false)) }))
        ] })
      ];
    }
    case "divider": {
      counters.paragraphs += 1;
      return [new Paragraph({ border: { bottom: { color: "CBD5E1", space: 1, style: "single", size: 6 } } })];
    }
  }
}

function paragraph(
  runs: readonly InlineRun[],
  counters: { paragraphs: number },
  options: Omit<IParagraphOptions, "children"> = {},
  color?: string
): Paragraph {
  counters.paragraphs += 1;
  return new Paragraph({ ...options, children: textRuns(runs, color) });
}

function textRuns(runs: readonly InlineRun[], color?: string): TextRun[] {
  return runs.map((run) => new TextRun({
    text: run.text,
    ...(run.bold === undefined ? {} : { bold: run.bold }),
    ...(run.italic === undefined ? {} : { italics: run.italic }),
    ...(run.underline === true ? { underline: {} } : {}),
    ...(run.code === true ? { style: "Code" } : {}),
    ...(color === undefined ? {} : { color })
  }));
}

function cell(runs: readonly InlineRun[], counters: { paragraphs: number }, header: boolean): TableCell {
  return new TableCell({
    ...(header ? { shading: { type: ShadingType.CLEAR, fill: "E2E8F0" } } : {}),
    children: [paragraph(runs.map((run) => header ? { ...run, bold: true } : run), counters)]
  });
}
