import { extname } from "node:path";

import { strFromU8, unzipSync } from "fflate";

import type { InlineRun, RichDocumentBlock, RichDocumentLeafBlock, RichDocumentSource } from "./contracts.js";
import { validateXlsxPackage } from "./xlsx-renderer.js";

export type PptxValidation = {
  readonly format: "pptx";
  readonly byteLength: number;
  readonly slideCount: number;
  readonly packageEntryCount: number;
};

const MAX_PPTX_BYTES = 50_000_000;

type SlideLike = {
  addText(text: unknown, options?: unknown): void;
  addShape(shape: unknown, options?: unknown): void;
  addTable(rows: unknown, options?: unknown): void;
  addImage(options: unknown): void;
  addChart(type: unknown, data: unknown, options?: unknown): void;
};
type PptxLike = {
  layout: string;
  author: string;
  subject: string;
  title: string;
  company: string;
  lang: string;
  theme: unknown;
  readonly ChartType: Record<"line" | "pie" | "bar", unknown>;
  readonly ShapeType: Record<"roundRect" | "line", unknown>;
  defineSlideMaster(options: unknown): void;
  addSlide(masterName?: string): SlideLike;
  write(options: unknown): Promise<string | ArrayBuffer | Blob | Uint8Array>;
};
type PptxConstructor = new () => PptxLike;

export async function renderPptx(
  source: RichDocumentSource,
  resolveAsset: (workspacePath: string) => string
): Promise<{ readonly bytes: Buffer; readonly validation: PptxValidation }> {
  const loaded = await import("pptxgenjs");
  const Constructor = loaded.default as unknown as PptxConstructor;
  const pptx = new Constructor();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Nexora";
  pptx.subject = "Generated by the Nexora Office capability";
  pptx.title = source.title;
  pptx.company = "Nexora";
  pptx.lang = source.locale;
  pptx.theme = {
    headFontFace: source.theme.font === "serif" ? "Georgia" : "Microsoft YaHei",
    bodyFontFace: source.theme.font === "serif" ? "Georgia" : "Microsoft YaHei",
    lang: source.locale
  };
  pptx.defineSlideMaster({
    title: "NEXORA",
    background: { color: source.theme.surface === "dark" ? "0F172A" : "F8FAFC" },
    objects: [
      { rect: { x: 0, y: 0, w: 0.12, h: 7.5, fill: { color: hex(source.theme.primaryColor) }, line: { color: hex(source.theme.primaryColor) } } },
      { text: { text: source.title, options: { x: 0.45, y: 7.08, w: 7.8, h: 0.18, fontSize: 8, color: source.theme.surface === "dark" ? "CBD5E1" : "64748B", margin: 0 } } }
    ],
    slideNumber: { x: 12.35, y: 7.05, w: 0.45, h: 0.2, fontSize: 8, color: "64748B", align: "right", margin: 0 }
  });

  const titleSlide = pptx.addSlide("NEXORA");
  titleSlide.addText(source.title, { x: 0.8, y: 2.25, w: 11.7, h: 1.1, fontSize: 30, bold: true, color: hex(source.theme.primaryColor), margin: 0, breakLine: false, fit: "shrink" });
  titleSlide.addText("Generated by Nexora", { x: 0.82, y: 3.55, w: 5, h: 0.35, fontSize: 14, color: "64748B", margin: 0 });
  let slideCount = 1;
  for (const block of source.blocks) {
    const slide = pptx.addSlide("NEXORA");
    slideCount += 1;
    renderBlock(slide, block, source, resolveAsset, pptx);
  }

  const output = await pptx.write({ outputType: "nodebuffer", compression: true });
  const bytes = Buffer.from(output as Uint8Array);
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_PPTX_BYTES) throw new Error(`Generated PPTX byte length ${bytes.byteLength} is outside the safe limit.`);
  const packageValidation = validatePptxPackage(bytes);
  const actualSlides = packageValidation.slideCount;
  if (actualSlides !== slideCount) throw new Error(`Generated PPTX expected ${slideCount} slides but reopened with ${actualSlides}.`);
  return { bytes, validation: { format: "pptx", byteLength: bytes.byteLength, slideCount, packageEntryCount: packageValidation.packageEntryCount } };
}

export function validatePptxPackage(bytes: Uint8Array): { readonly packageEntryCount: number; readonly slideCount: number } {
  const entries = unzipSync(bytes);
  for (const required of ["[Content_Types].xml", "_rels/.rels", "ppt/presentation.xml"]) {
    if (entries[required] === undefined) throw new Error(`Generated PPTX is missing required package entry ${required}.`);
  }
  const embedded = Object.keys(entries).filter((name) => !name.endsWith("/") && /^ppt\/embeddings\//u.test(name));
  for (const name of embedded) {
    if (!/^ppt\/embeddings\/Microsoft_Excel_Worksheet\d+\.xlsx$/u.test(name)) {
      throw new Error(`Generated PPTX contains a forbidden embedded object: ${name}.`);
    }
    validateXlsxPackage(entries[name]!);
  }
  const forbidden = Object.keys(entries).find((name) => !name.endsWith("/") && /(?:vbaProject|activeX)/iu.test(name));
  if (forbidden !== undefined) throw new Error(`Generated PPTX contains forbidden active content: ${forbidden}.`);
  const slideCount = Object.keys(entries).filter((name) => /^ppt\/slides\/slide\d+\.xml$/u.test(name)).length;
  if (slideCount === 0) throw new Error("Generated PPTX contains no slides.");
  return { packageEntryCount: Object.keys(entries).length, slideCount };
}

export function readPptxSlideXml(bytes: Uint8Array): readonly string[] {
  const entries = unzipSync(bytes);
  return Object.entries(entries)
    .filter(([name]) => /^ppt\/slides\/slide\d+\.xml$/u.test(name))
    .sort(([left], [right]) => left.localeCompare(right, "en", { numeric: true }))
    .map(([, value]) => strFromU8(value));
}

function renderBlock(
  slide: SlideLike,
  block: RichDocumentBlock,
  source: RichDocumentSource,
  resolveAsset: (workspacePath: string) => string,
  pptx: PptxLike
): void {
  if (block.type === "columns") {
    slide.addText("Highlights", titleOptions(source));
    const width = 11.8 / block.columns.length;
    block.columns.forEach((column, index) => {
      const content = column.map(leafText).filter(Boolean).join("\n\n");
      slide.addShape(pptx.ShapeType.roundRect, { x: 0.65 + index * width, y: 1.45, w: width - 0.25, h: 4.95, rectRadius: 0.06, fill: { color: "FFFFFF", transparency: source.theme.surface === "dark" ? 82 : 0 }, line: { color: "CBD5E1" } });
      slide.addText(content, { x: 0.88 + index * width, y: 1.72, w: width - 0.7, h: 4.35, fontSize: 16, color: textColor(source), valign: "top", breakLine: false, fit: "shrink", margin: 0.04 });
    });
    return;
  }
  switch (block.type) {
    case "heading":
      slide.addText(text(block.runs), { ...titleOptions(source), fontSize: block.level === 1 ? 28 : 24 });
      slide.addText("Section", { x: 0.72, y: 1.65, w: 3, h: 0.35, color: "64748B", fontSize: 14, margin: 0 });
      break;
    case "paragraph":
    case "callout":
      slide.addText(block.type === "callout" ? "Key point" : "Narrative", titleOptions(source));
      slide.addText(text(block.runs), { x: 0.75, y: 1.5, w: 11.8, h: 4.9, fontSize: 22, color: textColor(source), breakLine: false, fit: "shrink", valign: "mid", margin: 0.12, fill: block.type === "callout" ? { color: "DBEAFE" } : undefined });
      break;
    case "list":
      slide.addText("Key items", titleOptions(source));
      slide.addText(block.items.map((item, index) => ({ text: text(item), options: { bullet: block.ordered ? { type: "number" } : { type: "bullet" }, breakLine: index < block.items.length - 1 } })), { x: 0.8, y: 1.45, w: 11.5, h: 5.25, fontSize: 20, color: textColor(source), breakLine: false, fit: "shrink", margin: 0.08, paraSpaceAfterPt: 12 });
      break;
    case "table":
      slide.addText(block.caption === undefined ? block.blockId : text(block.caption), titleOptions(source));
      slide.addTable([block.headers.map(text), ...block.rows.map((row) => row.map(text))], { x: 0.7, y: 1.4, w: 11.9, h: 5.5, fontSize: 14, color: textColor(source), border: { color: "CBD5E1", pt: 1 }, fill: "FFFFFF", bold: false, margin: 0.05, autoFit: false, rowH: 0.45 });
      break;
    case "metric":
      slide.addText(text(block.label), titleOptions(source));
      slide.addText(text(block.value), { x: 0.8, y: 2.0, w: 7.2, h: 1.25, fontSize: 42, bold: true, color: hex(source.theme.primaryColor), margin: 0 });
      if (block.delta !== undefined) slide.addText(text(block.delta), { x: 0.82, y: 3.4, w: 4, h: 0.55, fontSize: 22, color: hex(source.theme.accentColor), margin: 0 });
      if (block.note !== undefined) slide.addText(text(block.note), { x: 0.82, y: 4.2, w: 10.8, h: 1.2, fontSize: 18, color: textColor(source), margin: 0, fit: "shrink" });
      break;
    case "image": {
      const path = resolveAsset(block.assetPath);
      const extension = extname(path).toLowerCase();
      if (![".png", ".jpg", ".jpeg"].includes(extension)) throw new Error(`PPTX supports PNG and JPEG image assets; ${block.assetPath} is ${extension || "unknown"}.`);
      slide.addText(block.caption === undefined ? block.alt : text(block.caption), titleOptions(source));
      slide.addImage({ path, x: 1.2, y: 1.35, w: 10.8, h: 5.45, transparency: 0 });
      break;
    }
    case "chart": {
      slide.addText(block.title ?? "Chart", titleOptions(source));
      const chartType = block.chartType === "line" ? pptx.ChartType.line : block.chartType === "pie" ? pptx.ChartType.pie : pptx.ChartType.bar;
      slide.addChart(chartType, block.series.map((series) => ({ name: series.name, labels: block.categories, values: series.values })), { x: 0.8, y: 1.35, w: 11.6, h: 5.55, showLegend: block.showLegend, showTitle: false, showValue: false, catAxisLabelFontSize: 12, valAxisLabelFontSize: 11, chartColors: block.series.map((series) => hex(series.color ?? source.theme.accentColor)) });
      break;
    }
    case "divider":
      slide.addText(source.title, titleOptions(source));
      slide.addShape(pptx.ShapeType.line, { x: 1.0, y: 3.7, w: 11.0, h: 0, line: { color: hex(source.theme.accentColor), pt: 2 } });
      break;
  }
}

function titleOptions(source: RichDocumentSource) {
  return { x: 0.7, y: 0.48, w: 11.8, h: 0.65, fontSize: 25, bold: true, color: hex(source.theme.primaryColor), margin: 0, fit: "shrink" as const };
}
function text(runs: readonly InlineRun[]): string { return runs.map(({ text: value }) => value).join(""); }
function hex(color: string): string { return color.slice(1).toUpperCase(); }
function textColor(source: RichDocumentSource): string { return source.theme.surface === "dark" ? "E2E8F0" : "172033"; }

function leafText(block: RichDocumentLeafBlock): string {
  switch (block.type) {
    case "heading":
    case "paragraph":
    case "callout": return text(block.runs);
    case "list": return block.items.map((item) => `• ${text(item)}`).join("\n");
    case "table": return `${block.caption === undefined ? "Table" : text(block.caption)}: ${block.rows.length} rows`;
    case "metric": return `${text(block.label)}\n${text(block.value)}${block.delta === undefined ? "" : `  ${text(block.delta)}`}`;
    case "image": return block.alt;
    case "chart": return block.title ?? "Chart";
    case "divider": return "";
  }
}
